# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(828, 421)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setAnimated(True)
        mainWindow.setDocumentMode(False)
        mainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 811, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.bot = QtWidgets.QWidget()
        self.bot.setObjectName("bot")
        self.START_BUTTON = QtWidgets.QPushButton(self.bot)
        self.START_BUTTON.setGeometry(QtCore.QRect(400, 260, 111, 41))
        self.START_BUTTON.setObjectName("START_BUTTON")
        self.groupBox_2 = QtWidgets.QGroupBox(self.bot)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 241, 341))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 50, 31, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 31, 16))
        self.label_3.setObjectName("label_3")
        self.HP_BAR = QtWidgets.QProgressBar(self.groupBox_2)
        self.HP_BAR.setGeometry(QtCore.QRect(40, 50, 201, 16))
        self.HP_BAR.setProperty("value", 0)
        self.HP_BAR.setObjectName("HP_BAR")
        self.MP_BAR = QtWidgets.QProgressBar(self.groupBox_2)
        self.MP_BAR.setGeometry(QtCore.QRect(40, 100, 201, 16))
        self.MP_BAR.setProperty("value", 0)
        self.MP_BAR.setObjectName("MP_BAR")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 170, 21, 16))
        self.label_10.setObjectName("label_10")
        self.EXP_LABEL = QtWidgets.QLabel(self.groupBox_2)
        self.EXP_LABEL.setGeometry(QtCore.QRect(60, 170, 141, 20))
        self.EXP_LABEL.setScaledContents(False)
        self.EXP_LABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.EXP_LABEL.setObjectName("EXP_LABEL")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 230, 21, 16))
        self.label_12.setObjectName("label_12")
        self.OU_LABEL = QtWidgets.QLabel(self.groupBox_2)
        self.OU_LABEL.setGeometry(QtCore.QRect(40, 230, 181, 16))
        self.OU_LABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.OU_LABEL.setObjectName("OU_LABEL")
        self.LVL_LABEL = QtWidgets.QLabel(self.groupBox_2)
        self.LVL_LABEL.setGeometry(QtCore.QRect(60, 20, 31, 21))
        self.LVL_LABEL.setObjectName("LVL_LABEL")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_11.setObjectName("label_11")
        self.EXP_PER_HOUR = QtWidgets.QLabel(self.groupBox_2)
        self.EXP_PER_HOUR.setGeometry(QtCore.QRect(60, 190, 141, 20))
        self.EXP_PER_HOUR.setAlignment(QtCore.Qt.AlignCenter)
        self.EXP_PER_HOUR.setObjectName("EXP_PER_HOUR")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 190, 41, 16))
        self.label_14.setObjectName("label_14")
        self.OU_PER_HOUR = QtWidgets.QLabel(self.groupBox_2)
        self.OU_PER_HOUR.setGeometry(QtCore.QRect(50, 250, 161, 16))
        self.OU_PER_HOUR.setAlignment(QtCore.Qt.AlignCenter)
        self.OU_PER_HOUR.setObjectName("OU_PER_HOUR")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 250, 41, 16))
        self.label_16.setObjectName("label_16")
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setGeometry(QtCore.QRect(10, 210, 221, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setGeometry(QtCore.QRect(10, 150, 221, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.HP_CUR = QtWidgets.QLabel(self.groupBox_2)
        self.HP_CUR.setGeometry(QtCore.QRect(50, 70, 71, 20))
        self.HP_CUR.setScaledContents(False)
        self.HP_CUR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.HP_CUR.setObjectName("HP_CUR")
        self.label4 = QtWidgets.QLabel(self.groupBox_2)
        self.label4.setGeometry(QtCore.QRect(120, 70, 21, 20))
        self.label4.setScaledContents(False)
        self.label4.setAlignment(QtCore.Qt.AlignCenter)
        self.label4.setObjectName("label4")
        self.HP_MAX = QtWidgets.QLabel(self.groupBox_2)
        self.HP_MAX.setGeometry(QtCore.QRect(140, 70, 61, 20))
        self.HP_MAX.setScaledContents(False)
        self.HP_MAX.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.HP_MAX.setObjectName("HP_MAX")
        self.MP_CUR = QtWidgets.QLabel(self.groupBox_2)
        self.MP_CUR.setGeometry(QtCore.QRect(60, 120, 61, 20))
        self.MP_CUR.setScaledContents(False)
        self.MP_CUR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MP_CUR.setObjectName("MP_CUR")
        self.label3 = QtWidgets.QLabel(self.groupBox_2)
        self.label3.setGeometry(QtCore.QRect(120, 120, 21, 20))
        self.label3.setScaledContents(False)
        self.label3.setAlignment(QtCore.Qt.AlignCenter)
        self.label3.setObjectName("label3")
        self.MP_MAX = QtWidgets.QLabel(self.groupBox_2)
        self.MP_MAX.setGeometry(QtCore.QRect(140, 120, 61, 20))
        self.MP_MAX.setScaledContents(False)
        self.MP_MAX.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.MP_MAX.setObjectName("MP_MAX")
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setGeometry(QtCore.QRect(10, 270, 221, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(60, 290, 121, 16))
        self.label_13.setObjectName("label_13")
        self.PLAYER_X = QtWidgets.QLabel(self.groupBox_2)
        self.PLAYER_X.setGeometry(QtCore.QRect(20, 312, 61, 21))
        self.PLAYER_X.setLineWidth(1)
        self.PLAYER_X.setAlignment(QtCore.Qt.AlignCenter)
        self.PLAYER_X.setObjectName("PLAYER_X")
        self.PLAYER_Y = QtWidgets.QLabel(self.groupBox_2)
        self.PLAYER_Y.setGeometry(QtCore.QRect(90, 312, 61, 21))
        self.PLAYER_Y.setLineWidth(1)
        self.PLAYER_Y.setAlignment(QtCore.Qt.AlignCenter)
        self.PLAYER_Y.setObjectName("PLAYER_Y")
        self.PLAYER_Z = QtWidgets.QLabel(self.groupBox_2)
        self.PLAYER_Z.setGeometry(QtCore.QRect(160, 312, 61, 21))
        self.PLAYER_Z.setLineWidth(1)
        self.PLAYER_Z.setAlignment(QtCore.Qt.AlignCenter)
        self.PLAYER_Z.setObjectName("PLAYER_Z")
        self.EXP_PERCENT = QtWidgets.QLabel(self.groupBox_2)
        self.EXP_PERCENT.setGeometry(QtCore.QRect(200, 170, 41, 20))
        self.EXP_PERCENT.setTextFormat(QtCore.Qt.AutoText)
        self.EXP_PERCENT.setScaledContents(False)
        self.EXP_PERCENT.setAlignment(QtCore.Qt.AlignCenter)
        self.EXP_PERCENT.setObjectName("EXP_PERCENT")
        self.groupBox_3 = QtWidgets.QGroupBox(self.bot)
        self.groupBox_3.setGeometry(QtCore.QRect(260, 10, 251, 241))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.label_15.setObjectName("label_15")
        self.MOB_LVL = QtWidgets.QLabel(self.groupBox_3)
        self.MOB_LVL.setGeometry(QtCore.QRect(60, 20, 91, 21))
        self.MOB_LVL.setObjectName("MOB_LVL")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(160, 20, 21, 21))
        self.label_18.setObjectName("label_18")
        self.MOB_ID = QtWidgets.QLabel(self.groupBox_3)
        self.MOB_ID.setGeometry(QtCore.QRect(180, 20, 61, 21))
        self.MOB_ID.setObjectName("MOB_ID")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(10, 50, 31, 16))
        self.label_20.setObjectName("label_20")
        self.MOB_HP_BAR = QtWidgets.QProgressBar(self.groupBox_3)
        self.MOB_HP_BAR.setGeometry(QtCore.QRect(40, 50, 211, 16))
        self.MOB_HP_BAR.setProperty("value", 0)
        self.MOB_HP_BAR.setObjectName("MOB_HP_BAR")
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setGeometry(QtCore.QRect(10, 150, 231, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(20, 100, 141, 21))
        self.label_17.setObjectName("label_17")
        self.MOB_TO_PLAYER_LEN = QtWidgets.QLabel(self.groupBox_3)
        self.MOB_TO_PLAYER_LEN.setGeometry(QtCore.QRect(160, 100, 71, 21))
        self.MOB_TO_PLAYER_LEN.setAlignment(QtCore.Qt.AlignCenter)
        self.MOB_TO_PLAYER_LEN.setObjectName("MOB_TO_PLAYER_LEN")
        self.MOB_HP_MAX = QtWidgets.QLabel(self.groupBox_3)
        self.MOB_HP_MAX.setGeometry(QtCore.QRect(130, 70, 51, 20))
        self.MOB_HP_MAX.setScaledContents(False)
        self.MOB_HP_MAX.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.MOB_HP_MAX.setObjectName("MOB_HP_MAX")
        self.MOB_HP_CUR = QtWidgets.QLabel(self.groupBox_3)
        self.MOB_HP_CUR.setGeometry(QtCore.QRect(50, 70, 61, 20))
        self.MOB_HP_CUR.setScaledContents(False)
        self.MOB_HP_CUR.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MOB_HP_CUR.setObjectName("MOB_HP_CUR")
        self.label4_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label4_2.setGeometry(QtCore.QRect(110, 70, 21, 20))
        self.label4_2.setScaledContents(False)
        self.label4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label4_2.setObjectName("label4_2")
        self.NEAR_ITEMS = QtWidgets.QLabel(self.groupBox_3)
        self.NEAR_ITEMS.setGeometry(QtCore.QRect(130, 170, 111, 20))
        self.NEAR_ITEMS.setScaledContents(False)
        self.NEAR_ITEMS.setAlignment(QtCore.Qt.AlignCenter)
        self.NEAR_ITEMS.setObjectName("NEAR_ITEMS")
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setGeometry(QtCore.QRect(20, 170, 101, 16))
        self.label_22.setObjectName("label_22")
        self.NEAR_AI = QtWidgets.QLabel(self.groupBox_3)
        self.NEAR_AI.setGeometry(QtCore.QRect(130, 190, 111, 20))
        self.NEAR_AI.setScaledContents(False)
        self.NEAR_AI.setAlignment(QtCore.Qt.AlignCenter)
        self.NEAR_AI.setObjectName("NEAR_AI")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(20, 190, 101, 16))
        self.label_23.setObjectName("label_23")
        self.NEAR_PLAYERS = QtWidgets.QLabel(self.groupBox_3)
        self.NEAR_PLAYERS.setGeometry(QtCore.QRect(130, 210, 111, 20))
        self.NEAR_PLAYERS.setScaledContents(False)
        self.NEAR_PLAYERS.setAlignment(QtCore.Qt.AlignCenter)
        self.NEAR_PLAYERS.setObjectName("NEAR_PLAYERS")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(20, 210, 101, 16))
        self.label_24.setObjectName("label_24")
        self.MOB_TO_CENTER_LEN = QtWidgets.QLabel(self.groupBox_3)
        self.MOB_TO_CENTER_LEN.setGeometry(QtCore.QRect(160, 130, 71, 21))
        self.MOB_TO_CENTER_LEN.setAlignment(QtCore.Qt.AlignCenter)
        self.MOB_TO_CENTER_LEN.setObjectName("MOB_TO_CENTER_LEN")
        self.label_38 = QtWidgets.QLabel(self.groupBox_3)
        self.label_38.setGeometry(QtCore.QRect(20, 130, 121, 21))
        self.label_38.setObjectName("label_38")
        self.STOP_BUTTON = QtWidgets.QPushButton(self.bot)
        self.STOP_BUTTON.setGeometry(QtCore.QRect(400, 310, 111, 41))
        self.STOP_BUTTON.setObjectName("STOP_BUTTON")
        self.READY_BUTTON = QtWidgets.QPushButton(self.bot)
        self.READY_BUTTON.setGeometry(QtCore.QRect(260, 260, 131, 91))
        self.READY_BUTTON.setObjectName("READY_BUTTON")
        self.groupBox_4 = QtWidgets.QGroupBox(self.bot)
        self.groupBox_4.setGeometry(QtCore.QRect(520, 10, 271, 241))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(10, 50, 101, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_4)
        self.label_28.setGeometry(QtCore.QRect(10, 80, 101, 21))
        self.label_28.setObjectName("label_28")
        self.ATTACK_SP_SL = QtWidgets.QSlider(self.groupBox_4)
        self.ATTACK_SP_SL.setGeometry(QtCore.QRect(109, 50, 131, 22))
        self.ATTACK_SP_SL.setMinimum(6)
        self.ATTACK_SP_SL.setMaximum(20)
        self.ATTACK_SP_SL.setOrientation(QtCore.Qt.Horizontal)
        self.ATTACK_SP_SL.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.ATTACK_SP_SL.setTickInterval(2)
        self.ATTACK_SP_SL.setObjectName("ATTACK_SP_SL")
        self.RUN_SPEED_SL = QtWidgets.QSlider(self.groupBox_4)
        self.RUN_SPEED_SL.setGeometry(QtCore.QRect(109, 20, 131, 22))
        self.RUN_SPEED_SL.setMinimum(5)
        self.RUN_SPEED_SL.setMaximum(30)
        self.RUN_SPEED_SL.setTracking(True)
        self.RUN_SPEED_SL.setOrientation(QtCore.Qt.Horizontal)
        self.RUN_SPEED_SL.setInvertedAppearance(False)
        self.RUN_SPEED_SL.setInvertedControls(False)
        self.RUN_SPEED_SL.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.RUN_SPEED_SL.setTickInterval(2)
        self.RUN_SPEED_SL.setObjectName("RUN_SPEED_SL")
        self.ATTACK_DL_SL = QtWidgets.QSlider(self.groupBox_4)
        self.ATTACK_DL_SL.setGeometry(QtCore.QRect(109, 80, 131, 22))
        self.ATTACK_DL_SL.setMaximum(30)
        self.ATTACK_DL_SL.setOrientation(QtCore.Qt.Horizontal)
        self.ATTACK_DL_SL.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.ATTACK_DL_SL.setTickInterval(2)
        self.ATTACK_DL_SL.setObjectName("ATTACK_DL_SL")
        self.RUN_SPEED_L = QtWidgets.QLabel(self.groupBox_4)
        self.RUN_SPEED_L.setGeometry(QtCore.QRect(240, 20, 31, 21))
        self.RUN_SPEED_L.setAlignment(QtCore.Qt.AlignCenter)
        self.RUN_SPEED_L.setObjectName("RUN_SPEED_L")
        self.ATTACK_SP_L = QtWidgets.QLabel(self.groupBox_4)
        self.ATTACK_SP_L.setGeometry(QtCore.QRect(240, 50, 31, 21))
        self.ATTACK_SP_L.setAlignment(QtCore.Qt.AlignCenter)
        self.ATTACK_SP_L.setObjectName("ATTACK_SP_L")
        self.ATTACK_DL_L = QtWidgets.QLabel(self.groupBox_4)
        self.ATTACK_DL_L.setGeometry(QtCore.QRect(240, 80, 31, 21))
        self.ATTACK_DL_L.setAlignment(QtCore.Qt.AlignCenter)
        self.ATTACK_DL_L.setObjectName("ATTACK_DL_L")
        self.CH_UPDATE = QtWidgets.QPushButton(self.groupBox_4)
        self.CH_UPDATE.setGeometry(QtCore.QRect(10, 120, 251, 31))
        self.CH_UPDATE.setObjectName("CH_UPDATE")
        self.CH_SET = QtWidgets.QPushButton(self.groupBox_4)
        self.CH_SET.setGeometry(QtCore.QRect(10, 160, 251, 31))
        self.CH_SET.setObjectName("CH_SET")
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setGeometry(QtCore.QRect(10, 200, 251, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CHEATS_X_P = QtWidgets.QPushButton(self.widget)
        self.CHEATS_X_P.setObjectName("CHEATS_X_P")
        self.horizontalLayout.addWidget(self.CHEATS_X_P)
        self.CHEATS_X_M = QtWidgets.QPushButton(self.widget)
        self.CHEATS_X_M.setObjectName("CHEATS_X_M")
        self.horizontalLayout.addWidget(self.CHEATS_X_M)
        self.CHEATS_Y_P = QtWidgets.QPushButton(self.widget)
        self.CHEATS_Y_P.setObjectName("CHEATS_Y_P")
        self.horizontalLayout.addWidget(self.CHEATS_Y_P)
        self.CHEATS_Y_M = QtWidgets.QPushButton(self.widget)
        self.CHEATS_Y_M.setObjectName("CHEATS_Y_M")
        self.horizontalLayout.addWidget(self.CHEATS_Y_M)
        self.CHEATS_Z_P = QtWidgets.QPushButton(self.widget)
        self.CHEATS_Z_P.setObjectName("CHEATS_Z_P")
        self.horizontalLayout.addWidget(self.CHEATS_Z_P)
        self.CHEATS_Z_M = QtWidgets.QPushButton(self.widget)
        self.CHEATS_Z_M.setObjectName("CHEATS_Z_M")
        self.horizontalLayout.addWidget(self.CHEATS_Z_M)
        self.SAFE_CONFIG = QtWidgets.QPushButton(self.bot)
        self.SAFE_CONFIG.setGeometry(QtCore.QRect(520, 260, 271, 41))
        self.SAFE_CONFIG.setObjectName("SAFE_CONFIG")
        self.LOAD_CONFIG = QtWidgets.QPushButton(self.bot)
        self.LOAD_CONFIG.setGeometry(QtCore.QRect(520, 310, 271, 41))
        self.LOAD_CONFIG.setObjectName("LOAD_CONFIG")
        self.tabWidget.addTab(self.bot, "")
        self.skills = QtWidgets.QWidget()
        self.skills.setObjectName("skills")
        self.tableWidget = QtWidgets.QTableWidget(self.skills)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 321, 351))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.groupBox = QtWidgets.QGroupBox(self.skills)
        self.groupBox.setGeometry(QtCore.QRect(340, 10, 451, 351))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.HEALTH_POITION_TIMEOUT = QtWidgets.QSpinBox(self.groupBox)
        self.HEALTH_POITION_TIMEOUT.setGeometry(QtCore.QRect(190, 250, 42, 22))
        self.HEALTH_POITION_TIMEOUT.setProperty("value", 6)
        self.HEALTH_POITION_TIMEOUT.setObjectName("HEALTH_POITION_TIMEOUT")
        self.MAX_MOB_DISTANCE = QtWidgets.QSpinBox(self.groupBox)
        self.MAX_MOB_DISTANCE.setGeometry(QtCore.QRect(190, 160, 42, 22))
        self.MAX_MOB_DISTANCE.setProperty("value", 20)
        self.MAX_MOB_DISTANCE.setObjectName("MAX_MOB_DISTANCE")
        self.JUMP_OFFSET = QtWidgets.QSpinBox(self.groupBox)
        self.JUMP_OFFSET.setGeometry(QtCore.QRect(190, 100, 42, 22))
        self.JUMP_OFFSET.setProperty("value", 5)
        self.JUMP_OFFSET.setObjectName("JUMP_OFFSET")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 151, 21))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 250, 151, 21))
        self.label_9.setObjectName("label_9")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 151, 20))
        self.label_2.setObjectName("label_2")
        self.NEED_LOOT = QtWidgets.QCheckBox(self.groupBox)
        self.NEED_LOOT.setGeometry(QtCore.QRect(190, 10, 16, 21))
        self.NEED_LOOT.setText("")
        self.NEED_LOOT.setChecked(True)
        self.NEED_LOOT.setObjectName("NEED_LOOT")
        self.MANA_POITION_TIMEOUT = QtWidgets.QSpinBox(self.groupBox)
        self.MANA_POITION_TIMEOUT.setGeometry(QtCore.QRect(190, 220, 42, 22))
        self.MANA_POITION_TIMEOUT.setProperty("value", 6)
        self.MANA_POITION_TIMEOUT.setObjectName("MANA_POITION_TIMEOUT")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 151, 21))
        self.label_5.setObjectName("label_5")
        self.MOB_TIMEOUT = QtWidgets.QSpinBox(self.groupBox)
        self.MOB_TIMEOUT.setGeometry(QtCore.QRect(190, 190, 42, 22))
        self.MOB_TIMEOUT.setProperty("value", 10)
        self.MOB_TIMEOUT.setObjectName("MOB_TIMEOUT")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 151, 21))
        self.label_6.setObjectName("label_6")
        self.MAX_DISTANCE = QtWidgets.QSpinBox(self.groupBox)
        self.MAX_DISTANCE.setGeometry(QtCore.QRect(190, 130, 42, 22))
        self.MAX_DISTANCE.setProperty("value", 25)
        self.MAX_DISTANCE.setObjectName("MAX_DISTANCE")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 151, 21))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 151, 21))
        self.label_8.setObjectName("label_8")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(10, 280, 151, 21))
        self.label_19.setObjectName("label_19")
        self.HEALTH_POITION_PERCENT = QtWidgets.QSpinBox(self.groupBox)
        self.HEALTH_POITION_PERCENT.setGeometry(QtCore.QRect(190, 280, 42, 22))
        self.HEALTH_POITION_PERCENT.setProperty("value", 70)
        self.HEALTH_POITION_PERCENT.setObjectName("HEALTH_POITION_PERCENT")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(10, 310, 151, 21))
        self.label_21.setObjectName("label_21")
        self.MANA_POITION_PERCENT = QtWidgets.QSpinBox(self.groupBox)
        self.MANA_POITION_PERCENT.setGeometry(QtCore.QRect(190, 310, 42, 22))
        self.MANA_POITION_PERCENT.setProperty("value", 50)
        self.MANA_POITION_PERCENT.setObjectName("MANA_POITION_PERCENT")
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setGeometry(QtCore.QRect(10, 40, 151, 20))
        self.label_25.setObjectName("label_25")
        self.NEAR_PLAYERS_WORK = QtWidgets.QCheckBox(self.groupBox)
        self.NEAR_PLAYERS_WORK.setGeometry(QtCore.QRect(190, 40, 16, 21))
        self.NEAR_PLAYERS_WORK.setText("")
        self.NEAR_PLAYERS_WORK.setChecked(False)
        self.NEAR_PLAYERS_WORK.setObjectName("NEAR_PLAYERS_WORK")
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        self.line_5.setGeometry(QtCore.QRect(240, 10, 21, 331))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_29 = QtWidgets.QLabel(self.groupBox)
        self.label_29.setGeometry(QtCore.QRect(260, 20, 101, 20))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setGeometry(QtCore.QRect(260, 50, 101, 20))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox)
        self.label_31.setGeometry(QtCore.QRect(260, 80, 101, 20))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setGeometry(QtCore.QRect(260, 110, 101, 20))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox)
        self.label_33.setGeometry(QtCore.QRect(260, 140, 121, 20))
        self.label_33.setObjectName("label_33")
        self.NEAR_PLAYERS_RUN = QtWidgets.QCheckBox(self.groupBox)
        self.NEAR_PLAYERS_RUN.setGeometry(QtCore.QRect(190, 70, 20, 21))
        self.NEAR_PLAYERS_RUN.setText("")
        self.NEAR_PLAYERS_RUN.setChecked(False)
        self.NEAR_PLAYERS_RUN.setObjectName("NEAR_PLAYERS_RUN")
        self.label_34 = QtWidgets.QLabel(self.groupBox)
        self.label_34.setGeometry(QtCore.QRect(10, 70, 151, 20))
        self.label_34.setObjectName("label_34")
        self.LOOT_KEY = QtWidgets.QComboBox(self.groupBox)
        self.LOOT_KEY.setGeometry(QtCore.QRect(370, 20, 69, 22))
        self.LOOT_KEY.setObjectName("LOOT_KEY")
        self.ATTACK_KEY = QtWidgets.QComboBox(self.groupBox)
        self.ATTACK_KEY.setGeometry(QtCore.QRect(370, 50, 69, 22))
        self.ATTACK_KEY.setObjectName("ATTACK_KEY")
        self.HP_KEY = QtWidgets.QComboBox(self.groupBox)
        self.HP_KEY.setGeometry(QtCore.QRect(370, 80, 69, 22))
        self.HP_KEY.setObjectName("HP_KEY")
        self.MP_KEY = QtWidgets.QComboBox(self.groupBox)
        self.MP_KEY.setGeometry(QtCore.QRect(370, 110, 69, 22))
        self.MP_KEY.setObjectName("MP_KEY")
        self.RUN_KEY = QtWidgets.QComboBox(self.groupBox)
        self.RUN_KEY.setGeometry(QtCore.QRect(370, 140, 69, 22))
        self.RUN_KEY.setObjectName("RUN_KEY")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(250, 170, 231, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_36 = QtWidgets.QLabel(self.groupBox_5)
        self.label_36.setGeometry(QtCore.QRect(10, 140, 131, 20))
        self.label_36.setObjectName("label_36")
        self.label_35 = QtWidgets.QLabel(self.groupBox_5)
        self.label_35.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.label_35.setObjectName("label_35")
        self.MOB_START_LVL = QtWidgets.QSpinBox(self.groupBox_5)
        self.MOB_START_LVL.setGeometry(QtCore.QRect(80, 100, 42, 22))
        self.MOB_START_LVL.setMaximum(200)
        self.MOB_START_LVL.setProperty("value", 40)
        self.MOB_START_LVL.setObjectName("MOB_START_LVL")
        self.label_37 = QtWidgets.QLabel(self.groupBox_5)
        self.label_37.setGeometry(QtCore.QRect(130, 100, 16, 21))
        self.label_37.setObjectName("label_37")
        self.MOB_END_LVL = QtWidgets.QSpinBox(self.groupBox_5)
        self.MOB_END_LVL.setGeometry(QtCore.QRect(150, 100, 42, 22))
        self.MOB_END_LVL.setMaximum(200)
        self.MOB_END_LVL.setProperty("value", 41)
        self.MOB_END_LVL.setObjectName("MOB_END_LVL")
        self.MOB_CRITICAL_LVL = QtWidgets.QSpinBox(self.groupBox_5)
        self.MOB_CRITICAL_LVL.setGeometry(QtCore.QRect(150, 140, 42, 22))
        self.MOB_CRITICAL_LVL.setMaximum(200)
        self.MOB_CRITICAL_LVL.setProperty("value", 45)
        self.MOB_CRITICAL_LVL.setObjectName("MOB_CRITICAL_LVL")
        self.label_75 = QtWidgets.QLabel(self.groupBox_5)
        self.label_75.setGeometry(QtCore.QRect(10, 65, 111, 21))
        self.label_75.setObjectName("label_75")
        self.OTHER_ACTIVATE = QtWidgets.QCheckBox(self.groupBox_5)
        self.OTHER_ACTIVATE.setGeometry(QtCore.QRect(125, 65, 16, 21))
        self.OTHER_ACTIVATE.setText("")
        self.OTHER_ACTIVATE.setChecked(False)
        self.OTHER_ACTIVATE.setObjectName("OTHER_ACTIVATE")
        self.USE_RADAR = QtWidgets.QCheckBox(self.groupBox_5)
        self.USE_RADAR.setGeometry(QtCore.QRect(125, 30, 16, 21))
        self.USE_RADAR.setText("")
        self.USE_RADAR.setChecked(False)
        self.USE_RADAR.setObjectName("USE_RADAR")
        self.label_76 = QtWidgets.QLabel(self.groupBox_5)
        self.label_76.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.label_76.setObjectName("label_76")
        self.tabWidget.addTab(self.skills, "")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.RUN_SPEED_SL.valueChanged['int'].connect(self.RUN_SPEED_L.setNum)
        self.ATTACK_SP_SL.valueChanged['int'].connect(self.ATTACK_SP_L.setNum)
        self.ATTACK_DL_SL.valueChanged['int'].connect(self.ATTACK_DL_L.setNum)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "LC RUS Bot"))
        self.START_BUTTON.setText(_translate("mainWindow", "СТАРТ"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Статус персонажа"))
        self.label.setText(_translate("mainWindow", "ХП:"))
        self.label_3.setText(_translate("mainWindow", "МП:"))
        self.HP_BAR.setFormat(_translate("mainWindow", "%p%"))
        self.MP_BAR.setFormat(_translate("mainWindow", "%p%"))
        self.label_10.setText(_translate("mainWindow", "ОП:"))
        self.EXP_LABEL.setText(_translate("mainWindow", "0"))
        self.label_12.setText(_translate("mainWindow", "ОУ:"))
        self.OU_LABEL.setText(_translate("mainWindow", "0"))
        self.LVL_LABEL.setText(_translate("mainWindow", "0"))
        self.label_11.setText(_translate("mainWindow", "Уровень:"))
        self.EXP_PER_HOUR.setText(_translate("mainWindow", "0"))
        self.label_14.setText(_translate("mainWindow", "ОП/час:"))
        self.OU_PER_HOUR.setText(_translate("mainWindow", "0"))
        self.label_16.setText(_translate("mainWindow", "ОУ/час:"))
        self.HP_CUR.setText(_translate("mainWindow", "0"))
        self.label4.setText(_translate("mainWindow", "/"))
        self.HP_MAX.setText(_translate("mainWindow", "0"))
        self.MP_CUR.setText(_translate("mainWindow", "0"))
        self.label3.setText(_translate("mainWindow", "/"))
        self.MP_MAX.setText(_translate("mainWindow", "0"))
        self.label_13.setText(_translate("mainWindow", "Координаты персонажа"))
        self.PLAYER_X.setText(_translate("mainWindow", "X"))
        self.PLAYER_Y.setText(_translate("mainWindow", "Y"))
        self.PLAYER_Z.setText(_translate("mainWindow", "Z"))
        self.EXP_PERCENT.setText(_translate("mainWindow", "0%"))
        self.groupBox_3.setTitle(_translate("mainWindow", "Выбранная Цель"))
        self.label_15.setText(_translate("mainWindow", "Уровень:"))
        self.MOB_LVL.setText(_translate("mainWindow", "0"))
        self.label_18.setText(_translate("mainWindow", "ID:"))
        self.MOB_ID.setText(_translate("mainWindow", "0"))
        self.label_20.setText(_translate("mainWindow", "ХП:"))
        self.MOB_HP_BAR.setFormat(_translate("mainWindow", "%p%"))
        self.label_17.setText(_translate("mainWindow", "Расстояние от персонажа:"))
        self.MOB_TO_PLAYER_LEN.setText(_translate("mainWindow", "0"))
        self.MOB_HP_MAX.setText(_translate("mainWindow", "0"))
        self.MOB_HP_CUR.setText(_translate("mainWindow", "0"))
        self.label4_2.setText(_translate("mainWindow", "/"))
        self.NEAR_ITEMS.setText(_translate("mainWindow", "0"))
        self.label_22.setText(_translate("mainWindow", "Предметов рядом:"))
        self.NEAR_AI.setText(_translate("mainWindow", "0"))
        self.label_23.setText(_translate("mainWindow", "AI рядом:"))
        self.NEAR_PLAYERS.setText(_translate("mainWindow", "0"))
        self.label_24.setText(_translate("mainWindow", "Люди рядом:"))
        self.MOB_TO_CENTER_LEN.setText(_translate("mainWindow", "0"))
        self.label_38.setText(_translate("mainWindow", "Расстояние от центра:"))
        self.STOP_BUTTON.setText(_translate("mainWindow", "СТОП"))
        self.READY_BUTTON.setText(_translate("mainWindow", "НАЖАТЬ\n"
"КОГДА\n"
"ВСЕ ЗАГРУЗИТСЯ"))
        self.groupBox_4.setTitle(_translate("mainWindow", "Читы"))
        self.label_26.setText(_translate("mainWindow", "Скорость бега:"))
        self.label_27.setText(_translate("mainWindow", "Скорость атаки:"))
        self.label_28.setText(_translate("mainWindow", "Дистанция атаки:"))
        self.RUN_SPEED_L.setText(_translate("mainWindow", "0"))
        self.ATTACK_SP_L.setText(_translate("mainWindow", "0"))
        self.ATTACK_DL_L.setText(_translate("mainWindow", "0"))
        self.CH_UPDATE.setText(_translate("mainWindow", "Обновить"))
        self.CH_SET.setText(_translate("mainWindow", "Установить"))
        self.CHEATS_X_P.setText(_translate("mainWindow", "+X"))
        self.CHEATS_X_M.setText(_translate("mainWindow", "-X"))
        self.CHEATS_Y_P.setText(_translate("mainWindow", "+Y"))
        self.CHEATS_Y_M.setText(_translate("mainWindow", "-Y"))
        self.CHEATS_Z_P.setText(_translate("mainWindow", "+Z"))
        self.CHEATS_Z_M.setText(_translate("mainWindow", "-Z"))
        self.SAFE_CONFIG.setText(_translate("mainWindow", "СОХРАНИТЬ КОНФИГ В ФАЙЛ"))
        self.LOAD_CONFIG.setText(_translate("mainWindow", "ЗАГРУЗИТЬ КОНФИГ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.bot), _translate("mainWindow", "Бот"))
        self.label_7.setText(_translate("mainWindow", "Таймаут урона мобу:"))
        self.label_9.setText(_translate("mainWindow", "Откат бутылок ХП:"))
        self.label_2.setText(_translate("mainWindow", "Подбирать предметы:"))
        self.label_5.setText(_translate("mainWindow", "Радиус рабочей зоны:"))
        self.label_6.setText(_translate("mainWindow", "Радиус поиска мобов:"))
        self.label_4.setText(_translate("mainWindow", "Длина прыжка при возврате:"))
        self.label_8.setText(_translate("mainWindow", "Откат бутылок МП:"))
        self.label_19.setText(_translate("mainWindow", "Порог бутылок ХП (%):"))
        self.label_21.setText(_translate("mainWindow", "Порог бутылок МП (%):"))
        self.label_25.setText(_translate("mainWindow", "Не работать при людях:"))
        self.label_29.setText(_translate("mainWindow", "Кнопка подбора:"))
        self.label_30.setText(_translate("mainWindow", "Кнопка атаки:"))
        self.label_31.setText(_translate("mainWindow", "Банки ХП:"))
        self.label_32.setText(_translate("mainWindow", "Банки МП:"))
        self.label_33.setText(_translate("mainWindow", "Кнопка побега:"))
        self.label_34.setText(_translate("mainWindow", "Убегать, если рядом люди:"))
        self.groupBox_5.setTitle(_translate("mainWindow", "Прочее"))
        self.label_36.setText(_translate("mainWindow", "Убегать, если LVL выше:"))
        self.label_35.setText(_translate("mainWindow", "LVL мобов: от"))
        self.label_37.setText(_translate("mainWindow", "до"))
        self.label_75.setText(_translate("mainWindow", "Проверять LVL мобов:"))
        self.label_76.setText(_translate("mainWindow", "Использовать радар:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.skills), _translate("mainWindow", "Настройки"))

